### PR TITLE
remove craig wright

### PR DESCRIPTION
**Pull request by mg98**
Craig Wright is not confirmed to be the creator of Bitcoin/ Satoshi Nakamoto [1]. Saying so is spreading fake information.

[1] https://en.wikipedia.org/wiki/Craig_Steven_Wright

### CODE REVIEW

**Comment by 1Hyena** [comment]
Relying on Wikipedia is much less appropriate than relying on a primary source.

As you can see here, Craig Wright is the author of the Bitcoin whitepaper:
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3440802

Evidence that Craig Wrigh is Satoshi Nakamoto is also revealed in the [lawsuit between Craig Wright and Ira Kleiman](https://storage.courtlistener.com/recap/gov.uscourts.flsd.521536/gov.uscourts.flsd.521536.600.13_1.pdf).

**Comment by mg98** [comment]
All we know is that Craig _claims_ to be the creator of Bitcoin. Your source is no evidence for this fact being true and I will argue that it is very easy to publish fake information on SSRN and at the same time actually extremely hard to do the same on Wikipedia.

His claim is highly disputed and it's clear that it is rejected by the mainstream and the scientific community.

At the very least, there is no safe evidence.

**Comment by 1Hyena** [comment]
I have personally met Satoshi Nakamoto and shaken hands with him. Craig Wright knows stuff about Bitcoin that only the creator of Bitcoin would know. Please study the lawsuit between Craig Wright and Ira Kleiman. There is plenty of evidence in the public now proving that Craig Wright indeed is Satoshi Nakamoto. This is not highly disputed by any means. It's now an established fact. You should update your knowledge base respectively.

**Comment by mg98** [comment]
I, unfortunately, do not have the time to study the case myself. So I have to outsource this. I don't know you, but if I have to believe either you or other people like V. Buterin and L. Fridman (which I highly respect), I will always prefer to rely on sources like https://www.youtube.com/watch?v=np7mIOaVIFU

**Comment by 1Hyena** [comment]
I have zero respect for the Soy Boy. Vitalik is not a boy genius, he just had a rich daddy who funded his stupid idea of creating a world computer that does not and will not ever scale. He also flees and hides from Craig so that he couldn't be served for the defamation. You should seriously reconsider your respect for V. Buterin and L. Fridman.

https://www.youtube.com/watch?v=DwfYG6FG71Y

**Comment by mg98** [comment]
I know the video hahaha but at this point, it is getting unobjective. I respect him for other reasons, and him eating booger does not correlate with those.

Although we are getting a little off-topic here... he **is** a boy genius! Try coming up with such an idea at this age or even in a lifetime.

Lex is also highly credible.

**Comment by mg98** [comment]
> Relying on Wikipedia is much less appropriate than relying on a primary source.
> 
> As you can see here, Craig Wright is the author of the Bitcoin whitepaper: https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3440802

Ah look, new evidence suggests another original author https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3977007

**Pull request closed without merging**
