### PR TITLE
New aluminum style.

### PR DESCRIPTION
**Pull request by Erstus**

### CODE REVIEW

**Comment by 1Hyena** [comment]
@Erstus 
Almost perfect but could you please change the texture of the page header and footer so that it would appear as it was higher than the tab content? See the picture attached where I have increased the brightness of the header to differentiate it from the tab content. The increased brightness is just an example of what kind of a change I expect. Let me know if you have any questions.
screenshot from 2017-01-01 22 37 37

**Comment by Erstus** [comment]
Thing was, that inset shadow was actually behind tab content, because if rised with z-depth, the content would become unclickable. This is now solved by disabling pointer events of shadow pseudo-div.
screenshot from 2017-01-02 18 17 50

**Comment by 1Hyena** [comment]
@Erstus 
I commented out background images and the page speed got an enormous boost. So at least now we know what made it so slow. It's the background images. The background size and position might also be contributing factors. Also shadows. So, perhaps you can find a workaround to this. Try commenting/uncommenting various combinations of the below code and check out whether page speed is affected.
```
body {
/*    background:url(gfx/color.png);
    background-size:cover;
    background-position: center center;*/
}
#cg {
	background: rgba(255, 255, 255, 0.35);
}
#cg-body {
    border-radius: 0.75rem;
/*    box-shadow: inset -0.25rem 0.5rem 10rem 0 rgba(0,0,0,0.5);
    background:url(gfx/color.png);
    background-size:cover;
    background-position: center center;*/
}

#cg-header{
/*    background:url(gfx/vertical.png);
    background-position: center center;*/
}
#cg-footer{
/*    background:url(gfx/vertical.png);
    background-position: center center;*/
}
#cg-body-texture {
/*    background:url(gfx/cross.png);
    background-position: center center;*/
    box-sizing:border-box;
    border:0.1rem solid rgba(0,0,0,0);
    border-radius: 0.75rem;
}
```

**Review by 1Hyena — APPROVED** [review]
Excellent! The message boxes are now styled very well. Thank you, @Erstus

**Pull request merged**
