### PR TITLE
Add ANSI color support

### PR DESCRIPTION
**Pull request by ghost**
Here's what it looks like: http://i.imgur.com/LviJ9J0.png

The colours are default CSS colours, maybe some other scheme would look better with the site?

### CODE REVIEW

**Comment by ghost** [comment]
Oh I forgot to mention this also supports bold, italics, underline and strikethrough. Feel free to disable it by commenting out the styles in main.css

**Comment by 1Hyena** [comment]
@eq Look super cool :) Thank you a lot! I will try to find time to review your changes as soon as possible but I currently don't know when I have time for this so it could take a couple of days.

**Comment by 1Hyena** [comment]
BTW you can test your code if you look at the message number `#3`, like this:
`cryptograffiti.info/#3`
because that message actually uses ANSI colours.

**Comment by 1Hyena** [comment]
screenshot from 2017-03-15 22 25 06
This looks awesome, I used your code to get this screenshot.

@eq  By the way, what is your motivation for accomplishing this task? I could afford to pay you 100 EUR worth of BTC if you wanted. Just let me know.

**Comment by 1Hyena** [comment]
Here's also 1 block chain message that contains ANSI colours... Looking pretty good in new cryptograffiti.

screenshot from 2017-03-16 21 03 42

**Comment by ghost** [comment]
Looks great! 👍 

> By the way, what is your motivation for accomplishing this task? I could afford to pay you 100 EUR worth of BTC if you wanted. Just let me know.

A friend showed me your website and I thought it was really neat. Saw there were some open issues and I had some free time so I figured I'd try to contribute.
I'll gladly accept the money, but please only do it if you can really afford it - address is 1PqiD5Efmmb3rGqHEoRucrJZ8qkWjV95oT. Thank you :)

**Comment by 1Hyena** [comment]
@eq Ok sent you the coins ;)
BTW I had a chance to review your pull request. Everything is great except one small little thing.
Here you are using escapeHtml: `span.innerHTML = processColours(escapeHtml(txt));`
which could potentially be vulnerable to XSS (I haven't verified it though).
It would be more secure and compatible with the rest of the code if you constructed the `span` elements via calls to JavaScript instead of using innerHTML directly. Do you think you could implement it like that? Let me know if you have any questions ;)

**Comment by ghost** [comment]
@1Hyena thank you so much!
I don't think it'll be vulnerable to XSS - that's what the `escapeHTML` function is for. I'd be happy to adjust the code to generate an element with JS calls instead, though. I'll get to work on it :)

**Comment by 1Hyena** [comment]
@eq Yes please do it because I am deliberately not using innerHTML nor escapeHTML functions anywhere else in the code. Those functions should generally be avoided due to XSS risks. Even if this particular change does not introduce XSS it is better to avoid evaluating untrusted input into HTML via innerHTML variable.

Also, I noticed that for ANSI art (the one I included in some previous comment) there are horizontal gaps between lines. Do you know if it is possible to get rid of those gaps (in all browsers)? If it's relatively easy to get rid of those gaps then I think we should do it but only for messages that contain ANSI ESC sequences, don't you think?

**Comment by ghost** [comment]
I think you can set the css property `line-height`, but I'm not quite sure.

**Comment by 1Hyena** [comment]
@eq Ok, if you have time you can play around with the `line-height` variable a little or perhaps research what google tells about it. If I remember correctly then this was difficult to achieve in a cross-browser way. But last time I checked was a couple of years ago, much could have changed since that.
edit:
Here's the test message: http://cryptograffiti.info/#2281

**Comment by ghost** [comment]
Alright, will do.

**Comment by ghost** [comment]
I've made it construct objects correctly over in the `remove-xss` branch. Going to do some testing before I add it to the PR

**Review by 1Hyena — APPROVED** [review]
Looking good, thank you a lot! :)

**Pull request merged**
